### PR TITLE
Suggestion: uniformly-styled default icons

### PR DESCRIPTION
**Pull request by BrotifyPacha**
Hello, I was able to find a full set of icons so that `step_back` icon wouldn't stick out, and would fit with the rest of them, also thought to replace square `terminate` icon with a cirlce one.

|before|suggest-uniformly-styled-icons-before|
|--|--|
|after|suggest-uniformly-styled-icons-after|

### CODE REVIEW

**Comment by rcarriga** [comment]
Thanks for the PR! I'd actually like to leave the terminate as the `stop` icon as it's semantically correct but I have realised it's the wrong code, which is why it looks off. Can you revert or update it to `` (code `0xead7`) as opposed to the previous `0x25a1`

**Comment by BrotifyPacha** [comment]
Sure! Changed the `terminate` icon to the one you gave.

Here's the preview:
image

**Comment by rcarriga** [comment]
Brilliant thanks!

**Comment by Spo0on** [comment]
Hiii. Since this update I'm no longer able to see icons. I fixed it temporarily by manually setting old icons but I'm wondering which font can actually display these new icons. I use DroidSansMono Nerd Font as my actual font.

**Comment by rcarriga** [comment]
They're using [codicons](https://github.com/microsoft/vscode-codicons). Nerd fonts are problematic because they often have issues with using icons that are not in private use areas (see https://github.com/ryanoasis/nerd-fonts/discussions/716) so I try to avoid using them by default because they're not consistent for all users

**Comment by rcarriga** [comment]
I've added a link to the docs and also linked to a fork which fixes some alignment issues with the base font.

**Comment by mishagantz** [comment]
It seems I'm too stupid to use this codicons, can't figure out what exactly should I do. 
Please add some option to use Nerd fonts

**Comment by rcarriga** [comment]
>  Please add some option to use Nerd fonts

This is already possible, all icons used are specified the in setup config.

Terminal emulators usually allow using fallback fonts which would be the preferred way of using the codicons font. Patching would definitely not be the expected way, but I can see iterm doesn't seem to support fallback fonts except for one for all non-ascii characters so it does seem necessary. PRs welcome :+1:

**Comment by rcarriga** [comment]
You don't need to disable the controls, just change the icons. I'd be happy to accept a PR to add icon suggestions for nerd fonts to the README for those that don't have codicons :smile:

**Pull request merged**
